baseURL: https://reborn.sabahlatan.com
languageCode: tr-tr
title: Sabahlatan
theme: binario
params:
  description: Sabahlamanın bahanesi, zevk alarak öğrenmenin adresi. Bilim, tarih, teknoloji, gündem, genel kültür, sanat, eğitim ve kalite.
permalinks:
  posts: /blog/:filename/
