name = "Gece"
license = "MIT"
licenselink = ""
description = ""
homepage = ""
demosite = ""
tags = ["blog", "dark", "disqus", "google analytics", "responsive"]
features = []
min_version = "0.1.0"

[author]
  name = ""
  homepage = ""
